### ISSUE TITLE
Example does not contain elm.json and uses source files

### ISSUE THREAD

**Issue by stephenreddek** [Holmusk/elmoji#1]
Thank you for creating this project! I'm very glad to see a native elm emoji picker.

When I pulled the repo to try out the picker, I found that the example `Main` file was not accompanied by an `elm.json`. After running `elm init` and installing the package, I also had to remove references to `Styles` and `Icons` since they are not exposed by the package. If you'd like, I can open a PR to make these changes.

**Comment by daniellok** [comment]
Thanks for opening this issue! The imports are just for the toggling button, so we can remove them and replace the icon with something more generic. I'd be happy to receive your PR!

**Comment by daniellok** [comment]
@stephenreddek I've made a couple changes to the example after looking over it again, and have removed the source file imports along the way. If you come across any issues I may have missed, please let me know!
